name: 🐞 Bug report
description: File a bug report
labels: [ "bug" ]
type: Bug
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >
        Please search to see if an
        [issue](https://github.com/SRGSSR/androidx-mediarouter-compose/issues)
        already exists for the bug you encountered.
      options:
        - label: I have searched existing issues and found no similar bug report.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the problem
      description: Describe the issue you encountered as precisely as possible.
    validations:
      required: true
  - type: textarea
    id: trace
    attributes:
      label: Relevant stack trace or log output
      description: Include a crash stack trace or a log output if available.
      render: shell
  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      description: Evaluate how easy it is to reproduce the issue.
      options:
        - Always
        - Difficult
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Include step-by-step instructions to reproduce the issue.
      placeholder: 1. …
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Library version
      description: Version of the library which is affected.
      placeholder: ex. 1.2.3
    validations:
      required: true
  - type: input
    id: system
    attributes:
      label: Android version(s)
      description: Version(s) of Android affected by this issue.
      placeholder: ex. Android 15, Android SDK 35
    validations:
      required: true
  - type: textarea
    id: sample
    attributes:
      label: Code sample
      description: Attach a code sample reproducing the issue if possible.
