blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/SRGSSR/androidx-mediarouter-compose/discussions
    about: Ask for questions and discuss with other members of the community
