name: 💡 Feature request
description: Request a feature or submit an idea you have
labels: [ "enhancement" ]
type: Enhancement
body:
  - type: checkboxes
    attributes:
      label: Is there an existing request for this?
      description: >
        Please search to see if a
        [request](https://github.com/SRGSSR/androidx-mediarouter-compose/issues)
        already exists for the feature you want.
      options:
        - label: I have searched existing requests and found no similar ideas.
          required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use case description
      description: Describe your use case in detail.
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: Provide us with a few acceptance criteria if possible.
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Propose a solution if you have an idea how the feature could be implemented.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions you might consider applicable.
