name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ github.token }}
      VERSION_NAME: ${{ github.ref_name }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version-file: .github/workflows/.java-version
          distribution: 'temurin'
      - name: Publish to GitHub Packages
        run: ./gradlew publish
      - name: Create GitHub Release
        run: gh release create ${{ env.VERSION_NAME }} --draft --generate-notes media-maestro/build/outputs/aar/media-maestro-release.aar
      - name: Generate Dokka documentation
        run: ./gradlew :dokkaGenerate
      - name: Deploy Dokka documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/dokka/html
          single-commit: true
